version: '3'
services:
 docker:
    image: voidp34r/invillia
    ports:
      - "8080:8080"
    depends_on:
      - docker-mysql
 docker-mysql:
    image: mysql
    environment:
      - MYSQL_DB=invillia
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass