version: '3'
services:
 docker:
    build:
      dockerfile: ./Dockerfile
      context: .
    # image: voidp34r/invillia
    container_name: invillia
    ports:
      - "8080:8080"
    networks:
      - development-network
    depends_on:
      - docker-mysql
    links :
      - docker-mysql
 docker-mysql:
    image: mysql
    restart : always
    networks:
      - development-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DB=invillia
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root,

networks:
    development-network:
        driver: bridge